service: http-handler

plugins:
  - serverless-apigw-binary
  - serverless-offline

custom:
  apigwBinary:
    types:
      - 'image/jpeg'

provider:
  name: aws
  runtime: nodejs8.10

functions:
  uploadImage:
    handler: handler.uploadImage
    role: arn:aws:iam::845275448803:role/lambda-http-handler
    events:
      - http:
          path: images
          method: post

  generateThumbnail:
    handler: handler.generateThumbnail
    role: arn:aws:iam::845275448803:role/lambda-http-handler
    events:
      - sns: arn:aws:sns:us-east-1:845275448803:s3-images-put-topic
